version: "3"

services:
  nest-setup:
    container_name: nest-setup
    build: .
    environment:
      - NODE_ENV=develop
    ports:
      - "3000:3000"
    volumes:
      - ./src:/var/prod/src
      - ./test:/var/prod/test
      - ./package.json:/var/prod/package.json
      
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: lm-robotica
    volumes:
      - ./mongo:/data/db
