version: "3"

services:
  nest-setup:
    container_name: nest-setup
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
        MONGODB: ${MONGODB}
    environment:
      - NODE_ENV=prod
    ports:
      - "3000:3000"
    volumes:
      - ./src:/var/prod/src
      - ./package.json:/var/prod/package.json
